Move common BPMN files to kogito-common (gennyq)
genny-project/gennyq pull request #144
Opened 2022-12-19 02:46 UTC by gardiary-obo

2022-12-19 04:44 UTC, adamcrow64 requested changes
You can remove the product specific suffixes 'GT andf GT2'.
LC stands for lifecycle and can remain

2022-12-21 04:54 UTC, varunshastry approved these changes

2023-01-16 01:29 UTC, varunshastry approved these changes

2023-01-16 01:42 UTC, jasperRob approved these changes
Overall, I'm happy with this. However the GennyService class may need some attention as it is using some deprecated code.

2023-01-16 01:50 UTC, merged