10.3.0 consolidated saved search
genny-project/gennyq pull request #170
Opened 2023-02-06 03:41 UTC by weslyvo81

This pull request is about cleaning up and improving saved search based on design doc.

2023-02-06 05:23 UTC, jasperRob requested changes
Please address these changes. Most of then are cleaning up some methods.

2023-02-06 05:23 UTC, jasperRob commented on kogitoq/gadaq/src/main/java/life/genny/gadaq/search/FilterGroupService.java
>      public  boolean isApply(String code) {
This should be:
```java
public boolean isApply(String code) {
    return Question.QUE_SAVED_SEARCH_APPLY.equalsIgnoreCase(code);
}
```

2023-02-06 05:23 UTC, jasperRob commented on kogitoq/gadaq/src/main/java/life/genny/gadaq/search/FilterGroupService.java
>          boolean result = false;
This should be:
```java
public boolean isColumnSelected(String code,String attCode) {
    if (Question.QUE_FILTER_COLUMN.equalsIgnoreCase(code)) {
        return true;
    }
    if (Attribute.LNK_FILTER_COLUMN.equalsIgnoreCase(attCode)) {
        return true;
    }
    return false;
```

2023-02-06 05:23 UTC, jasperRob commented on kogitoq/gadaq/src/main/java/life/genny/gadaq/search/FilterGroupService.java
>          boolean result = false;
This needs a clean up.

2023-02-06 05:23 UTC, jasperRob commented on kogitoq/gadaq/src/main/java/life/genny/gadaq/search/FilterGroupService.java
>      public boolean isBtnSearchSave(String code) {
This needs a clean up.

2023-02-06 05:23 UTC, jasperRob commented on kogitoq/gadaq/src/main/java/life/genny/gadaq/search/FilterGroupService.java
>      public boolean isBtnSearchDelete(String code) {
This needs a clean up.

2023-02-06 05:23 UTC, jasperRob commented on kogitoq/gadaq/src/main/java/life/genny/gadaq/search/FilterGroupService.java
>      public boolean isDetailDelete(String code) {
This needs a clean up.

2023-02-06 05:23 UTC, jasperRob commented on kogitoq/gadaq/src/main/java/life/genny/gadaq/search/FilterGroupService.java
> +        databaseUtils.deleteBaseEntityAndAttribute(user.getProductCode(), code);
Don't delete the BaseEntity, just update the EEntityStatus to DELETED

2023-02-06 05:23 UTC, jasperRob commented on kogitoq/gadaq/src/main/java/life/genny/gadaq/search/FilterGroupService.java
>      public String getQuestionCode(QEventMessage msg) {
This method seems redundant, we should not be returning an empty string.

2023-02-06 05:23 UTC, jasperRob commented on kogitoq/gadaq/src/main/java/life/genny/gadaq/search/FilterGroupService.java
>      public String getQuestionCode(QDataAnswerMessage msg) {
This method seems redundant, we should not be returning an empty string.

2023-02-06 05:23 UTC, jasperRob commented on kogitoq/gadaq/src/main/java/life/genny/gadaq/search/FilterGroupService.java
>      public String getAttributeCode(QDataAnswerMessage msg) {
We should not be returning an empty string. Also, consider the case that more than one item is present.

2023-02-06 05:23 UTC, jasperRob commented on kogitoq/gadaq/src/main/java/life/genny/gadaq/search/FilterGroupService.java
>      public String getTargetCode(QDataAnswerMessage msg) {
We should not be returning an empty string. Also, consider the case that more than one item is present.

2023-02-06 05:23 UTC, jasperRob commented on kogitoq/gadaq/src/main/java/life/genny/gadaq/search/FilterGroupService.java
>      public String getValue(QDataAnswerMessage msg) {
We should not be returning an empty string. Also, consider the case that more than one item is present.

2023-02-06 05:23 UTC, jasperRob commented on kogitoq/kogito-common/src/main/java/life/genny/kogito/common/service/FilterService.java
> +        if(coded) filter = new Filter(Attribute.PRI_CODE, Operator.EQUALS, value);
Don't use one line if statements, it goes against the google java style guide.

2023-02-06 06:14 UTC, weslyvo81 commented on kogitoq/gadaq/src/main/java/life/genny/gadaq/search/FilterGroupService.java
>      public  boolean isApply(String code) {
solved

2023-02-06 06:14 UTC, weslyvo81 commented on kogitoq/gadaq/src/main/java/life/genny/gadaq/search/FilterGroupService.java
>      public String getQuestionCode(QDataAnswerMessage msg) {
it is used in other methods

2023-02-06 06:15 UTC, weslyvo81 commented on kogitoq/gadaq/src/main/java/life/genny/gadaq/search/FilterGroupService.java
>      public String getTargetCode(QDataAnswerMessage msg) {
just get the first item

2023-02-06 06:15 UTC, weslyvo81 commented on kogitoq/gadaq/src/main/java/life/genny/gadaq/search/FilterGroupService.java
>      public String getAttributeCode(QDataAnswerMessage msg) {
just get the first item.

2023-02-06 06:15 UTC, weslyvo81 commented on kogitoq/gadaq/src/main/java/life/genny/gadaq/search/FilterGroupService.java
>      public String getValue(QDataAnswerMessage msg) {
just get the first item.

2023-02-07 00:13 UTC, jasperRob approved these changes
This will need a little more clean up in future, but good for now.

2023-02-07 00:28 UTC, varunshastry approved these changes

2023-02-07 00:28 UTC, merged