Fixed detached caps
genny-project/gennyq pull request #241
Opened 2023-03-17 12:22 UTC by Expressionless

* Detached Attributes are currently present in Capabilities System (legacy code, used to rely on Hibernate to manage ids). This is fixed now with a standardised way to create attributes that can be extended to bootq and other parts of the code if necessary
* Revised try/catch in FyodorUltra for missing rows. Can extend this to display the details of item not founds of every missed entity attribute for a row in a table
* Put on stricter validation for Capability-bearing base entities
* Removed some redundant methods and added some documentation

As a note we should strive to remove Object portrayals of primitives (Boolean instead of boolean, Integer instead of int etc) where possible. I understand this may not necessarily be possible for database fields but it is very possible for methods that return said primitives/objects

2023-03-17 12:27 UTC, Expressionless commented
![image](https://user-images.githubusercontent.com/17942849/225904249-e7b5911f-f4ca-4f79-b5a9-88fdeba171db.png)
Recommend using this for a VLD for potential missing DataTypes in local databases: DTT_CAPABILITY

<google-sheets-html-origin><style type="text/css"><!--td {border: 1px solid #cccccc;}br {mso-data-placement:same-cell;}--></style>

VLD_CAPABILITY | text | ^(\[((\")*(!)*[AEDV]\:[ASN](\")*(, )*)*\])+$ |   |   |   | Capabiilty String Invalid
-- | -- | -- | -- | -- | -- | --

2023-03-19 21:50 UTC, varunshastry requested changes

2023-03-19 21:50 UTC, varunshastry commented on qwandaq/src/main/java/life/genny/qwandaq/managers/capabilities/CapabilitiesManager.java
> +		if(filterable instanceof HBaseEntity be) {
The check should be for "BaseEntity" (life.genny.qwandaq.entity).

2023-03-19 21:50 UTC, varunshastry commented on qwandaq/src/main/java/life/genny/qwandaq/managers/capabilities/CapabilitiesManager.java
> +		if(filterable instanceof HEntityAttribute ea) {
The check should be for "EntityAttribute" (life.genny.qwandaq.attribute).

2023-03-19 21:50 UTC, varunshastry commented on qwandaq/src/main/java/life/genny/qwandaq/managers/capabilities/role/RoleManager.java
> +			children = beaUtils.getEntityAttribute(productCode, targetRole.getCode(), Attribute.LNK_CHILDREN, true, true);
"setValueString" is being called. Fetching attribute/datatype required?

2023-03-19 22:42 UTC, Expressionless commented
Updates made without IDE (may have build errors)

2023-03-20 00:28 UTC, jasperRob approved these changes

2023-03-20 00:34 UTC, varunshastry approved these changes

2023-03-20 00:34 UTC, merged