10.2.0 capabilities
genny-project/gennyq pull request #62
Opened 2022-09-14 03:10 UTC by Expressionless

implement hasCapability
implement addCapabilityToBaseEntity
implement createRole
implement helper functions
capabilities run through the cache first then the db
implement RoleBuilder for quality of life
Need to firm up what is happening with product codes to remove the product Code chain that exists in dbUtils, beUtils

2022-09-14 08:09 UTC, varunshastry requested changes

2022-09-14 08:09 UTC, varunshastry commented on qwandaq/src/main/java/life/genny/qwandaq/utils/capabilities/CapabilityUtils.java
> +		roleDef = beUtils.getBaseEntity("DEF_ROLE");
String to be extracted to GennyConstants

2022-09-14 08:09 UTC, varunshastry commented on qwandaq/src/main/java/life/genny/qwandaq/utils/capabilities/CapabilityUtils.java
> +		if (condition == null) {
StringUtils could be used to check for null/empty strings

2022-09-14 08:09 UTC, varunshastry commented on qwandaq/src/main/java/life/genny/qwandaq/utils/capabilities/CapabilityUtils.java
> +		RoleException re = new RoleException(
Exception object could be created only in case of exception. Otherwise, additional load on JVM & GC

2022-09-14 08:09 UTC, varunshastry commented on qwandaq/src/main/java/life/genny/qwandaq/utils/capabilities/CapabilityUtils.java
> +			if (beCapability.getValueString() == null) {
StringUtils to be used for checking null/empty

2022-09-19 02:44 UTC, Expressionless commented on qwandaq/src/main/java/life/genny/qwandaq/utils/capabilities/CapabilityUtils.java
> +		RoleException re = new RoleException(
Alright, but can we still have the error message as one string object? That way we are avoiding duplicating code still

2022-09-19 02:51 UTC, adamcrow64 approved these changes
LGTM

2022-09-19 02:51 UTC, merged